#!/bin/bash

STYPE="TV"

source $(dirname $(realpath "${0}"))/torrentscrape-core

SHOW="${1}"
WANTED="${2}"
UNWANTED="${3}"
MAXPAGES="${4}" # not needed in this module
URL="${5}"

parse() {
    SHOW="${1}"
    WANTED="${2}"
    UNWANTED="${3}"
    webget "${4}" | grep "magnet:?" | egrep "$WANTED" | egrep -v "$UNWANTED" > "${TMP}"

    while read MAGNETS; do

        MAGNET=`echo "$MAGNETS" | cut -f 2 -d '>' | cut -f 2 -d '"'`
#        $(scrape_series "${MAGNET}" "${SHOW}")
        scrape_series "${MAGNET}" "${SHOW}"

    done < "${TMP}"
}

parse "${SHOW}" "${WANTED}" "${UNWANTED}" "${URL}"

[[ -f "${TMP}" ]] && rm "${TMP}"
